root = true

browserfactory.explicit_wait_default_seconds=10
browserfactory.driver_type=CHROME
browserfactory.debugging=true
drivermanager.implicitly_wait_default_seconds=5
find.defautl_delay_seconds=2
